using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;

// Image 4: HG.RenderPipelines.Runtime.dll - Assembly: HG.RenderPipelines.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null - Types 37354-38879

namespace HG.Rendering.Runtime
{
	internal enum PassConstructorID // TypeDefIndex: 38509
	{
		UIImageBlur = 0,
		BinningPass = 1,
		ReflectionProbeBinning = 2,
		FoliageOccluder = 3,
		FoliageInteractive = 4,
		Sludge = 5,
		GpuClothSimulation = 6,
		LightClustering = 7,
		GPUDrivenCulling = 8,
		GPUParticleSimulation = 9,
		ParticleLighting = 10,
		CustomDepthOnly = 11,
		ShadowMap = 12,
		Atmosphere = 13,
		VolumetricFog = 14,
		BakeFogLut = 15,
		VolumetricCloud = 16,
		TerrainDeform = 17,
		TerrainVTBake = 18,
		InkSimulation = 19,
		TerrainDepthPrepass = 20,
		DepthPrepass = 21,
		Forward = 22,
		ForwardOpaque = 23,
		GBuffer = 24,
		Decal = 25,
		WaterSector = 26,
		WaterInteraction = 27,
		WaterDefaultDeferred = 28,
		WaterOnePassDeferred = 29,
		HZB = 30,
		DepthPyramid = 31,
		GTAO = 32,
		FakePlanarReflection = 33,
		HyperScreenSpaceReflection = 34,
		HyperRayTracingReflection = 35,
		ContactShadow = 36,
		CapsuleShadow = 37,
		ScreenSpaceShadowMask = 38,
		DeferredLighting = 39,
		Transparent = 40,
		OnePassDeferred = 41,
		Distortion = 42,
		LightShaft = 43,
		LightShaftApply = 44,
		Parafin = 45,
		DepthOfField = 46,
		MotionBlur = 47,
		TransparentAfterDOF = 48,
		TAAU = 49,
		MetalFXTemporal = 50,
		LensFlare = 51,
		UberPost = 52,
		MetalFXSpatial = 53,
		UIPP = 54,
		UI = 55,
		Multiblur = 56,
		ScreenSpaceOverlay = 57,
		WetnessMaskPass = 58,
		SetFinalTarget = 59,
		Count = 60
	}
}
