// Image 4: HG.RenderPipelines.Runtime.dll - Assembly: HG.RenderPipelines.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null - Types 37354-38879
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.None | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("HG.Rendering.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("HG.RenderPipelines.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("HG.RenderPipelines.Editor.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.HG.Runtime.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("HGRP_TestRunner")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.TextMeshPro.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Industrial.Materials.AVRD.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.HighDefinition-Tests.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.RenderPipelines.HighDefinition-Tests.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.GraphicTests.Performance.HDRP.Runtime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.GraphicTests.Performance.HDRP.Editor")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("TestRuntime")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Unity.Industrial.Materials.AVRD.Runtime")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]